apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: project
  labels: 
    app: mysql
    tier: mysql
    project: project
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysql
      tier: mysql
      project: project
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: project
    spec:
      containers:
      - name: nginx
        image: joindevops/mysql:1.0.0   ###nginx:1.14.2  ### srikanth9959/deployment:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: project
spec:
  selector: # labels will used here for selecting the pod
    app: mysql
    tier: mysql
    project: project
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306